### ISSUE TITLE
Feedback + a small typo

### ISSUE THREAD

**Issue by RohitY24** [microsoft/hack-workshop-power-apps#1]
The workshop is great. It is good enough for a beginner to follow & complete in a healthy duration of time.
The idea and content are neatly organized. 

There is a small typo I would like to raise. In the third step of creating a Power App, there is a small typo where Power Automate is written as Power AUtomate. Please fix that :)

Here is a snip of the same:
![image](https://user-images.githubusercontent.com/35281343/131227173-ca35dae8-32f7-4735-9d41-3740a5973418.png)

**Comment by leestott** [comment]
Thanks fixed
